
version: "3.7"

services:
  terraform:
    build: 
      context: .
      dockerfile: Dockerfile.terraform
    env_file: .env
    volumes:
      - .:/code
      - ~/.aws:/root/.aws
    working_dir: /code

  aws:
    build: 
      context: .
      dockerfile: Dockerfile.aws_3m
    env_file: .env
    volumes:
      - .:/code
      - ~/.aws:/root/.aws
    working_dir: /code

  wordpress:
    build: 
      context: .
      dockerfile: Dockerfile.wordpress
    env_file: .env
    volumes:
      - .:/code
    working_dir: /code