
version: "3.7"

services:
  terraform:
    build: 
      context: .
      dockerfile: Dockerfile.terraform
      args:
        version: 0.12.24
    env_file: .env
    volumes:
      - .:/code
      - ~/.aws:/root/.aws
    working_dir: /code

  aws:
    image: amazon/aws-cli:2.0.8
    env_file: .env
    volumes:
    - ~/.aws:/root/.aws