ARG version=18.04

FROM ubuntu:${version}

RUN apt-get update && \
		apt-get install make curl unzip sudo -y

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
		unzip awscliv2.zip && \
		sudo ./aws/install

ENTRYPOINT []
CMD [ "sh" ]